
# Test /ping endpoint
GET http://localhost:8002/ping

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

# Test get /summaries
GET http://localhost:8002/summaries

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

# Test get a specific /summaries/{id}
GET http://localhost:8002/summaries/1

###

# Test add new /summaries

POST http://localhost:8002/summaries/
Content-Type: application/json

{
  "url": "http://testdriven.io"
}

